/**
 * gen-ecosystem.ts — registered_casts + spy_casts からpm2設定を動的生成
 *
 * Usage: npx tsx scripts/gen-ecosystem.ts
 *
 * 出力: ecosystem.config.cjs (上書き)
 */

import 'dotenv/config';
import { createClient } from '@supabase/supabase-js';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const SUPABASE_URL = process.env.SUPABASE_URL!;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!;

if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
  console.error('Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env');
  process.exit(1);
}

const sb = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
  auth: { autoRefreshToken: false, persistSession: false },
});

interface CastRow {
  account_id: string;
  cast_name: string;
  display_name: string | null;
  stripchat_model_id: string | null;
}

async function main() {
  console.log('Loading casts from Supabase...');

  const [regResult, spyResult] = await Promise.all([
    sb.from('registered_casts')
      .select('account_id, cast_name, display_name, stripchat_model_id')
      .eq('is_active', true),
    sb.from('spy_casts')
      .select('account_id, cast_name, display_name, stripchat_model_id')
      .eq('is_active', true),
  ]);

  if (regResult.error) throw new Error(`registered_casts: ${regResult.error.message}`);
  if (spyResult.error) throw new Error(`spy_casts: ${spyResult.error.message}`);

  const registered = (regResult.data || []) as CastRow[];
  const spyCasts = (spyResult.data || []) as CastRow[];

  console.log(`Found: ${registered.length} registered + ${spyCasts.length} spy = ${registered.length + spyCasts.length} total`);

  // Generate pm2 app definitions
  const apps: object[] = [];
  const __filename = fileURLToPath(import.meta.url);
  const __dirname = path.dirname(__filename);
  const cwd = path.resolve(__dirname, '..');

  for (const cast of registered) {
    apps.push({
      name: `cast-${cast.cast_name}`,
      script: 'src/single-cast.ts',
      interpreter: 'node',
      interpreter_args: '--import tsx',
      cwd,
      env: {
        NODE_ENV: 'production',
        CAST_NAME: cast.cast_name,
        ACCOUNT_ID: cast.account_id,
        CAST_SOURCE: 'registered_casts',
        CAST_DISPLAY: cast.display_name || '',
        MODEL_ID: cast.stripchat_model_id || '',
      },
      autorestart: true,
      watch: false,
      max_memory_restart: '200M',
      log_file: `${cwd}/logs/${cast.cast_name}.log`,
      error_file: `${cwd}/logs/${cast.cast_name}-error.log`,
      out_file: `${cwd}/logs/${cast.cast_name}-out.log`,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      restart_delay: 10000,
      max_restarts: 50,
      min_uptime: '30s',
    });
  }

  for (const cast of spyCasts) {
    apps.push({
      name: `spy-${cast.cast_name}`,
      script: 'src/single-cast.ts',
      interpreter: 'node',
      interpreter_args: '--import tsx',
      cwd,
      env: {
        NODE_ENV: 'production',
        CAST_NAME: cast.cast_name,
        ACCOUNT_ID: cast.account_id,
        CAST_SOURCE: 'spy_casts',
        CAST_DISPLAY: cast.display_name || '',
        MODEL_ID: cast.stripchat_model_id || '',
      },
      autorestart: true,
      watch: false,
      max_memory_restart: '150M',
      log_file: `${cwd}/logs/${cast.cast_name}.log`,
      error_file: `${cwd}/logs/${cast.cast_name}-error.log`,
      out_file: `${cwd}/logs/${cast.cast_name}-out.log`,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      restart_delay: 15000,
      max_restarts: 30,
      min_uptime: '30s',
    });
  }

  // Write ecosystem.config.cjs
  const configContent = `// Auto-generated by scripts/gen-ecosystem.ts — DO NOT EDIT MANUALLY
// Regenerate: npx tsx scripts/gen-ecosystem.ts
// Generated: ${new Date().toISOString()}
// Casts: ${registered.length} registered + ${spyCasts.length} spy = ${apps.length} total

module.exports = {
  apps: ${JSON.stringify(apps, null, 2).replace(/"([^"]+)":/g, '$1:')}
};
`;

  const outPath = path.join(cwd, 'ecosystem.config.cjs');
  fs.writeFileSync(outPath, configContent, 'utf-8');
  console.log(`\nWritten: ${outPath}`);
  console.log(`\nProcess list (${apps.length} processes):`);
  for (const app of apps) {
    const a = app as { name: string; env: { CAST_SOURCE: string } };
    console.log(`  ${a.name} (${a.env.CAST_SOURCE})`);
  }
  console.log('\nNext: pm2 start ecosystem.config.cjs');
}

main().catch((err) => {
  console.error('Error:', err);
  process.exit(1);
});
